version: "3.9"

services:
  novax:
    container_name: novax
    build:
      context: .
      dockerfile: Dockerfile
    restart: unless-stopped

    environment:
      NODE_ENV: "production"
      TZ: "UTC"
      DefaultLocale: "en"
      APIPort: "${APIPort:-3000}"

      DiscordToken: "${DiscordToken:-CHANGE_ME}"
      DiscordIntents: "${DiscordIntents:-default}"
      LogLevel: "${LogLevel:-info}"
      Database: >
        {"alias": {"uri": "DATABASE_URI", "engine": "mongo", "poolSize": "0", "maxRetries": "3"}}

    ports:
      - "${APIPort:-3000}:${APIPort:-3000}"

    env_file:
      - .env
