namespace Zene.System;

table FileEntry {
  path: string (key);
  hash: [ubyte];
  size: uint;
}

table IntegrityPayload {
  timestamp: ulong;
  algorithm: string;
  files: [FileEntry];
  ignore_hash: [string];
}

table NodeDependency {
  name: string (key);
  version: string;
}

table ZeneManifest {
  id: string;
  name: string;
  version: string;
  description: string;
  author: string;
  dependencies: [string];
  zene_version: string;
  node_version: string;
  integrity: IntegrityPayload;
  node_dependencies: [NodeDependency];
}

root_type ZeneManifest;
