import { LIMITS as EMBED_LIMITS } from '#core/builders/embedBuilder/constants.js';
import {
    MAX_TEXT_CHARS_TOTAL,
    MAX_COMPONENTS_TOTAL,
    MAX_COMPONENTS_PER_ROW,
    MAX_CUSTOM_ID_LENGTH,
    MAX_LABEL_LENGTH,
} from '#core/builders/componentsv2Builder/constants.js';

export const PAGINATOR_LIMITS = {
    CONTENT_CHARS: 1900,
    EMBED_DESCRIPTION: EMBED_LIMITS.MAX_EMBED_DESCRIPTION,
    EMBED_TOTAL_CHARS: EMBED_LIMITS.MAX_TOTAL_EMBED_CHARS,
    CV2_TEXT_CHARS: MAX_TEXT_CHARS_TOTAL,
    CV2_TEXT_SAFE: 3800,
    MAX_COMPONENTS_TOTAL,
    MAX_COMPONENTS_PER_ROW,
    MAX_CUSTOM_ID_LENGTH,
    MAX_LABEL_LENGTH,
    MAX_ACTION_ROWS: 5,
    MAX_BUTTONS_WITH_UTIL: 2,
    MAX_BUTTONS_STANDALONE: 5,
} as const;

export type PaginatorLimits = typeof PAGINATOR_LIMITS;
